name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install

      # Drizzle migration
      - name: Run database migrations
        run: npx drizzle-kit migrate --execute --connection $DATABASE_URL

      - run: pnpm build

      - run: pnpm exec playwright install

      - run: pnpm test
